# This workflow will install Python dependencies, run checks and publish artifacts to PyPi.
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Publish

on:
  push:
    tags:
      - '*.*.*'

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: make install-dev
    - name: Run checks
      run: make check
    - name: Verify version
      run: |
        # Get the latest tag.
        latest_tag=$(git describe --tags `git rev-list --tags --max-count=1`)

        # Ensure we have this version set in pyproject.toml.
        version=`poetry version | cut -d' ' -f 2`
        if [ "$version" != "$latest_tag" ]
        then
            echo "Error! Project version $version does not match $latest_tag."
        else
            echo "Project version $version equals latest tag $latest_tag"
        fi
        test "$version" = "$latest_tag"
    - name: Build distribution packages for release
      run: |
        make release

        # Show built files in logs.
        ls -lh dist/
    - name: Publish to Test PyPi
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_TEST_API_TOKEN: ${{ secrets.PYPI_TEST_API_TOKEN }}
      run: make publish-test
    - name: Publish to PyPi
      env:
        PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: make publish
